FROM custom-rallly:latest AS runner
COPY --chown=nextjs:nodejs apps/web/.next/standalone ./
COPY --chown=nextjs:nodejs apps/web/.next/static ./apps/web/.next/static
COPY --chown=nextjs:nodejs apps/web/public ./apps/web/public
COPY packages/database/prisma ./prisma
COPY packages/database/prisma.config.ts ./
