FROM public.ecr.aws/docker/library/node:24-slim AS runner

ENV NEXT_TELEMETRY_DISABLED=1

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    openssl \
    zlib1g \
    libgcc-s1 \
    curl \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN addgroup --system nodejs \
  && adduser --system --ingroup nodejs --home /app --shell /bin/bash nextjs

RUN npm add prisma@7

COPY ./scripts/docker-start.sh ./
COPY ./packages/database/prisma ./prisma
COPY ./packages/database/prisma.config.ts ./

COPY --chown=nextjs:nodejs ./apps/web/.next/standalone ./
COPY --chown=nextjs:nodejs ./apps/web/.next/static ./apps/web/.next/static
COPY --chown=nextjs:nodejs ./apps/web/public ./apps/web/public

USER nextjs

ENV HOME=/app
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV LOG_LEVEL=warn
ENV API_BASE_URL=https://api.rallly.co

ARG SELF_HOSTED
ENV NEXT_PUBLIC_SELF_HOSTED=$SELF_HOSTED

EXPOSE 3000

HEALTHCHECK CMD curl --fail http://localhost:${PORT}/api/status || exit 1

CMD ["./docker-start.sh"]
